#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

_SYS := $(shell uname 2>/dev/null || echo Unknown)
_SYS := $(patsubst MSYS%,MSYS,$(_SYS))
_SYS := $(patsubst MINGW%,MinGW,$(_SYS))

#
# DailyBing
#
VERSION = 1.0.0
PACKAGE_NAME = DailyBing
APP_NAME = DailyBing
DailyBing_APPLICATION_ICON = DailyBing.png


#
# Resource files
#
DailyBing_RESOURCE_FILES = \
Resources/imageCache.plist \
Resources/avatar.png  \
Resources/catlock.png  \
Resources/catlock.py  \
Resources/DailyBing.png \
Resources/LockScreen  \

#
# Header files
#
DailyBing_HEADER_FILES = \
Source/AppDelegate.h \
Source/Interactive/DBWindow.h \
Source/Interactive/DBDataIndex.h \
Source/Interactive/DBImageView.h \
Source/Interactive/NSImage+SaveAs.h \
Source/LockScreen/BackView.h \
Source/LockScreen/LockWindow.h \
Source/LockScreen/NSImage+ProportionalScaling.h \


#
# Class files
#
DailyBing_OBJC_FILES = \
Source/main.m \
Source/AppDelegate.m \
Source/Interactive/DBWindow.m \
Source/Interactive/DBDataIndex.m \
Source/Interactive/DBImageView.m \
Source/Interactive/NSImage+SaveAs.m \
Source/LockScreen/BackView.m \
Source/LockScreen/LockWindow.m \
Source/LockScreen/NSImage+ProportionalScaling.m \

ifneq ($(filter $(_SYS),MSYS MinGW),)
OBJC_LIBS+= -ldispatch
endif

ifeq ($(_SYS),Linux)
OBJC_LIBS+= -ldispatch
endif

ifeq ($(_SYS),Darwin)
endif

ifeq ($(_SYS),FreeBSD)
endif

ifeq ($(_SYS),NetBSD)
endif

ifeq ($(_SYS),OpenBSD)
endif

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
