#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# DailyBing
#
VERSION = 1.0.0
PACKAGE_NAME = DailyBing
APP_NAME = DailyBing
DailyBing_APPLICATION_ICON = DailyBing.png


#
# Resource files
#
DailyBing_RESOURCE_FILES = \
Resources/DailyBing.png 

#
# Header files
#
DailyBing_HEADER_FILES = \
Window.h \
Controller.h

#
# Class files
#
DailyBing_OBJC_FILES = \
main.m \
Window.m \
Controller.m


#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
